# Generated by Django 2.1.7 on 2021-02-25 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img')),
                ('image_1', models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img')),
                ('image_2', models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img')),
                ('image_3', models.ImageField(blank=True, default='media/img/transparent.jpg', upload_to='media/img')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('event_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
